//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
// 

//
// TODO generated message class
//

import veins.base.utils.Coord;
import veins.modules.messages.DemoSafetyMessage;
import veins.base.utils.SimpleAddress;

namespace veins;

//extends é igual a herança
packet VisoesPlatoonMsg extends DemoSafetyMessage {
    int someField;
    int idLider;  //dados para estatística
    int idPlatoon;//dados para estatística
    double tempoEnvio;
    int qtdVisoesConhecidas;
    int  visoes[];//idLider, versão, qtdVeiculos  //trocar para visao
    int  visoesConhecidas1[];   
    int  visoesConhecidas2[];  
    int  visoesConhecidas3[];  
    int  visoesConhecidas4[];
    int  visoesConhecidas5[];
    int  visoesConhecidas6[];
    int  visoesConhecidas7[];
    int  visoesConhecidas8[];
    int  visoesConhecidas9[];
    int  visoesConhecidas10[];
    int  visoesConhecidas11[];
    int  visoesConhecidas12[];
    int  visoesConhecidas13[];
    int  visoesConhecidas14[];
    int  visoesConhecidas15[];
    int  visoesConhecidas16[];
    int  visoesConhecidas17[];
    int  visoesConhecidas18[];
    int  visoesConhecidas19[];
    int  visoesConhecidas20[];
    int  visoesConhecidas21[];
    int  visoesConhecidas22[];
    int  visoesConhecidas23[];
    int  visoesConhecidas24[];
    int  visoesConhecidas25[];
    int  visoesConhecidas26[];
    int  visoesConhecidas27[];
    int  visoesConhecidas28[];
    int  visoesConhecidas29[];
    int  visoesConhecidas30[];
    string texto;
}
